version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      - database
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./app:/var/www/html
    links:
      - database
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: library
      MYSQL_PASSWORD: library
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql